### ISSUE TITLE
Issue when upgrading to PHP8

### ISSUE THREAD

**Issue by hmriit** [123andy/redcap-em-user-agent-info#4]
I upgraded to PHP8 and User AGent was not happy.  I added brackets to the UserAgentInfo.php and that made it happy - line 25:

`
$options['ip-address'] = (isset($_SERVER['HTTP_CLIENT_IP'])?$_SERVER['HTTP_CLIENT_IP']):(isset($_SERVER['HTTP_X_FORWARDED_FOR'])?$_SERVER['HTTP_X_FORWARDED_FOR']):($_SERVER['REMOTE_ADDR']);
`

**Comment by 123andy** [comment]
Thanks - made the change.
